CoreCRM/ViewComponents/NavigationBarViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreCRM.Data;
using CoreCRM.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;

namespace CoreCRM.ViewComponents
{
    public class NavigationBarViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public NavigationBarViewComponent(ApplicationDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
			// if (_signInManager.IsSignedIn(HttpContext.User)) {
			//     wait FillModel();
			// }
            await Task.Delay(10);

			return View();
        }

        // private async Task FillModel(NavigationBarViewModel model)
        // {
        //     var user = await _userManager.GetUserAsync(HttpContext.User);
        //     if (user == null) return;

        //     model.UserName = user.UserName;

        //     _context.Entry(user).Reference(u => u.Profile).Load();
        //     model.UserAvatar = user.Profile.Avatar;

        //     _context.Entry(user).Reference(u => u.CustomUi);
        //     model.MainItems = GetMainMenu(user.CustomUi);
        //     model.MoreItems = GetMoreMenu(user.CustomUi);
        //     model.ShortcutMenu = GetShortcutMenu(user.CustomUi);
        //     model.UserMenu = GetUserMenu(user.CustomUi);

        //     model.MessageNum = GetMessageNum(user);
        //     model.ScheduleNum = GetScheduleNum(user);
        //     model.TaskNum = GetTaskNum(user);

        //     var descriptor = (ControllerActionDescriptor)ViewContext.ActionDescriptor;
        //     model.CurrentActionName = descriptor.ActionName;
        //     model.CurrentControllerName = descriptor.ControllerName;
        // }

        // private IEnumerable<NavigationBarItem> GetUserMenu(CustomUi customUi)
        // {
        //     var menuItems = new List<NavigationBarItem>();
        //     menuItems.Add(new NavigationBarItem() {
        //         Text = "测试用户",
        //         AreaName = "",
        //         ActionName = "Index",
        //         ControllerName = "Home"
        //     });

        //     return menuItems;
        // }

        // private IEnumerable<NavigationBarItem> GetShortcutMenu(CustomUi customUi)
        // {
        //     var menuItems = new List<NavigationBarItem>();
        //     menuItems.Add(new NavigationBarItem() {
        //         Text = "测试",
        //         AreaName = "",
        //         ActionName = "Index",
        //         ControllerName = "Home"
        //     });

        //     return menuItems;
        // }

        // private IEnumerable<NavigationBarItem> GetMoreMenu(CustomUi customUi)
        // {
        //     var menuItems = new List<NavigationBarItem>();
        //     menuItems.Add(new NavigationBarItem() {
        //         Text = "商机",
        //         AreaName = "",
        //         ActionName = "Index",
        //         ControllerName = "Home"
        //     });

        //     return menuItems;
        // }

        // private IEnumerable<NavigationBarItem> GetMainMenu(CustomUi customUi)
        // {
        //     var menuItems = new List<NavigationBarItem>();
        //     menuItems.Add(new NavigationBarItem() {
        //         Text = "线索",
        //         AreaName = "",
        //         ActionName = "Index",
        //         ControllerName = "Home"
        //     });
        //     menuItems.Add(new NavigationBarItem() {
        //         Text = "客户",
        //         AreaName = "",
        //         ActionName = "Index",
        //         ControllerName = "Home"
        //     });
        //     menuItems.Add(new NavigationBarItem() {
        //         Text = "商机",
        //         AreaName = "",
        //         ActionName = "Index",
        //         ControllerName = "Home"
        //     });

        //     return menuItems;
        // }

        // private int GetTaskNum(ApplicationUser user)
        // {
        //     return 0;
        // }

        // private int GetScheduleNum(ApplicationUser user)
        // {
        //     return 0;
        // }

        // private int GetMessageNum(ApplicationUser user)
        // {
        //     return 0;
        // }

    }
}

CoreCRM/Views/Shared/_FooterPartial.cshtml
<hr />
<footer>
    <p>&copy; 2016 - CoreCRM</p>
</footer>

CoreCRM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 10]><html class="old-id"><![endif]-->
<!--[if gte IE 10]>-->
<html>
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreCRM</title>

    @await Html.PartialAsync("_StylesPartial")
</head>
<body>
    <div class="old-browser-warning">
        <h1>您的浏览器版本太低，请使用 IE10 以上版本的浏览器，或者使用 Chrome，Firefox 等浏览器。</h1>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" class="body-content">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreCRM</a>
            </div>
            <div class="navbar-collapse collapse">
                @await Component.InvokeAsync("NavigationBar")
            </div>
        </div>
    </div>
    <div class="@ViewData["ContainerClass"]">
        @RenderBody()
        @await Html.PartialAsync("_FooterPartial")
    </div>

    @await Html.PartialAsync("_ScriptsPartial")
    @RenderSection("scripts", required: false)
</body>
</html>

CoreCRM/Views/Shared/_ScriptsPartial.cshtml
<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/highcharts/highcharts.src.js"></script>
    <script src="~/lib/vue/dist/vue.js"></script>
</environment>

<environment names="Staging,Production">
    <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>
    <script src="https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.js"
            asp-fallback-src="~/lib/jquery-ui/jquery-ui.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.ui">
    </script>
    <script src="https://cdn.bootcss.com/highcharts/5.0.5/highcharts.js"
            asp-fallback-src="~/lib/highcharts/highcharts.js"
            asp-fallback-test="window.Hightcharts">
    </script>
    <script src="https://cdn.bootcss.com/vue/2.1.4/vue.min.js"
            asp-fallback-src="~/lib/vue/dist/vue.min.js"
            asp-fallback-test="window.Vue">
    </script>

    <script src="https://cdn.bootcss.com/jquery-validate/1.14.0/jquery.validate.min.js"
            asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator">
    </script>
    <script src="https://cdn.bootcss.com/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"
            asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
    </script>
</environment>

CoreCRM/Views/Shared/_StylesPartial.cshtml
<environment names="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/themes/flick/jquery-ui.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/lib/highcharts/css/highcharts.css" />
    <link rel="stylesheet" href="~/lib/e-calendar/css/jquery.e-calendar.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</environment>
<environment names="Staging,Production">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css"
          asp-fallback-href="~/lib/font-awesome/css/font-awesome.min.css"
          asp-fallback-test-class="fa" asp-fallback-test-property="display" asp-fallback-test-value="inline-block" />
    <link rel="stylesheet" href="https://cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.css"
          asp-fallback-href="~/lib/jquery-ui/themes/flick/jquery-ui.min.css"
          asp-fallback-test-class="ui-helper-hidden" asp-fallback-test-property="display" asp-fallback-test-value="none" />
    <link rel="stylesheet" href="https://cdn.bootcss.com/highcharts/5.0.5/css/highcharts.css"
          asp-fallback-href="~/lib/highcharts/css/highcharts.css"
          asp-fallback-test-class="highcharts-container" asp-fallback-test-property="position" asp-fallback-test-value="relative"/>
    <link rel="stylesheet" href="~/lib/e-calendar/css/jquery.e-calendar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</environment>